### ISSUE TITLE
After clicking Imagery on/off the gray basemap does not come back

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-DemographicState#5]

**Comment by Jfairfield1** [comment]
Changed from 

`if (layer.id === "esriImagery" && layer.visible === true) {
                        baseLayer.hide();
                    } else {
                        baseLayer.show();
                    }`
to 
`if (layer.id === "esriImagery") {
                        if (layer.visible === true) {
                            baseLayer.hide();
                        } else { baseLayer.show(); }
                    }`

The first check was failing on every checkbox click.  This means baseLayer.show was being run every time a checkbox was clicked.  When this baseLayer is displayed, it covers up the imagery layer.
