### ISSUE TITLE
Legislative Districts should be sorted correctly

### ISSUE THREAD

**Issue by Jfairfield1** [AZMAG/map-DemographicState#50]
![image](https://cloud.githubusercontent.com/assets/13153086/23468059/03ab0b3e-fe5d-11e6-99f6-4d15413e82cf.png)

This should be corrected to sort the districts by number instead of alphabetical. 1,2,3 etc.

**Comment by vwolfley** [comment]
added a sort field to config.  Also had to add a field to MXD [SLDISTID] for ACS15_Legislative_Districts.
