### ISSUE TITLE
Legend items missing

### ISSUE THREAD

**Issue by Jfairfield1** [AZMAG/map-DemographicState#52]
Census Tracts, Zip codes, Streets toggle on/off, but don’t update in Legend

**Comment by Jfairfield1** [comment]
There is more to this task.  The Legend toggling by clicking the dropdowns is broken.

**Comment by vwolfley** [comment]
Not all items listed in the Layers Options will display in the Legend i.e[Census Tracts, ZIP codes, Streets, Imagery]  they were deemed not necessary to show.
Fixed all other items reguarding legend.
